export * from "./hero";
export * from "./faq";
export * from "./serviceIntro";
export * from "./testimonials";
export * from "./nav";
export * from "./social";
export * from "./howItWorks";
export * from "./userAgreement";
export * from "./policy";